export default {
  MARK_NOTIFICATION_AS_READ_BY_ID:'MARK_NOTIFICATION_AS_READ_BY_ID',
  MARK_AAL_NOTIFICATIONS_AS_READ_BY_ID:'MARK_AAL_NOTIFICATIONS_AS_READ_BY_ID',
  START_MARM_AS_READ:'START_MARM_AS_READ',
  FINISH_MARK_AS_READ:'FINISH_MARK_AS_READ',
  RECIVED_NOTIFICATIONS:'RECIVED_NOTIFICATIONS'
}